export const he = {
  appName: 'אישרו?',
  workspace: 'ניהול אירועים',
  hostId: 'מזהה מנהל',
  hostIdPlaceholder: 'ObjectId של Admin',
  events: 'אירועים',
  whatsapp: 'WhatsApp',
  guestsCommunication: 'מוזמנים ותקשורת',
  invitations: 'הזמנות',
  guestView: 'תצוגת מוזמן',
  settings: 'הגדרות',
  createEvent: 'אירוע חדש',
  createEventFlow: 'יצירת אירוע חדש',
  eventName: 'שם האירוע',
  eventNamePlaceholder: 'לדוגמה: ברית לאריאל',
  venuePlaceholder: 'לדוגמה: אולם האורנים',
  addressPlaceholder: 'לדוגמה: רחוב הרצל 10, הרצליה',
  expectedGuests: 'כמות מוזמנים משוערת',
  search: 'חיפוש אירוע',
  guests: 'מוזמנים',
  confirmed: 'אישרו',
  pending: 'ממתינים',
  eventDate: 'תאריך',
  venue: 'מקום',
  address: 'כתובת',
  wazeLink: 'קישור Waze',
  noEvents: 'עדיין אין אירועים להצגה',
  connectWhatsapp: 'חיבור WhatsApp',
  connect: 'התחבר',
  disconnect: 'נתק',
  refreshQr: 'רענן QR',
  status: 'סטטוס',
  scanQr: 'סרוק את הקוד מהאפליקציה בטלפון',
  disconnected: 'מנותק',
  qrReady: 'QR מוכן',
  connected: 'מחובר',
  apiHint: 'הממשק מוכן להתחברות ל-API המקומי.',
  selectedEvent: 'אירוע פעיל',
  activeEvent: 'אירוע פעיל',
  rsvpProgress: 'התקדמות אישורי הגעה',
  editInvitation: 'עריכת הזמנה',
  previewGuest: 'תצוגת מוזמן',
  setupEvent: 'הגדרות אירוע',
  openWhatsapp: 'WhatsApp',
  openGuestCommunication: 'מוזמנים והודעות',
  chooseEvent: 'בחר אירוע',
  invitationStudio: 'עיצוב ונוסח הזמנה',
  eventTheme: 'נושא האירוע',
  separateSeatingEvent: 'אירוע בהפרדה',
  separateSeatingEventDescription: 'נסמן לכל מוזמן כמה גברים וכמה נשים כדי להקל על ההושבה.',
  invitationText: 'נוסח ההזמנה',
  invitationTitle: 'כותרת',
  template: 'תבנית',
  saveDraft: 'שמור טיוטה',
  preview: 'תצוגה מקדימה',
  brit: 'ברית',
  wedding: 'חתונה',
  bar_mitzvah: 'בר מצווה',
  birthday: 'יום הולדת',
  corporate: 'עסקי',
  classic: 'קלאסי',
  warm: 'חם ואישי',
  elegant: 'אלגנטי',
  casual: 'קליל',
  authTitle: 'התחברות למערכת',
  authSubtitle: 'היכנס כדי לנהל אירועים, הזמנות ו-WhatsApp',
  email: 'אימייל',
  password: 'סיסמה',
  forgotPassword: 'שכחתי סיסמה',
  emailRequiredForReset: 'יש להזין אימייל כדי לשלוח קישור לאיפוס סיסמה.',
  passwordResetEmailSentTitle: 'מייל איפוס נשלח',
  passwordResetEmailSent: 'אם החשבון קיים, נשלח אליו קישור ליצירת סיסמה חדשה.',
  createNewPassword: 'יצירת סיסמה חדשה',
  createNewPasswordDescription: 'בחר סיסמה חזקה כדי להיכנס מחדש למערכת.',
  currentPassword: 'סיסמה נוכחית',
  newPassword: 'סיסמה חדשה',
  saveNewPassword: 'שמור סיסמה חדשה',
  changePassword: 'שינוי סיסמה',
  updatePassword: 'עדכן סיסמה',
  passwordUpdated: 'הסיסמה עודכנה',
  passwordUpdatedMessage: 'אפשר להשתמש בסיסמה החדשה בכניסה הבאה.',
  passwordTooWeak: 'הסיסמה לא מספיק חזקה. יש לעמוד בכללי החוזק לפני המשך.',
  passwordRequired: 'יש להזין סיסמה.',
  passwordWeak: 'סיסמה חלשה',
  passwordMedium: 'סיסמה בינונית',
  passwordStrong: 'סיסמה חזקה',
  passwordMissingRules: 'חסר',
  passwordRuleLength: 'לפחות 10 תווים',
  passwordRuleLowercase: 'אות קטנה באנגלית',
  passwordRuleUppercase: 'אות גדולה באנגלית',
  passwordRuleNumber: 'מספר',
  passwordRuleSpecial: 'תו מיוחד',
  login: 'התחבר',
  register: 'הרשמה',
  demoLogin: 'כניסה לדמו',
  eventSettings: 'הגדרות אירוע',
  eventPhone: 'מספר טלפון לאירוע',
  bitLink: 'קישור מתנות Bit',
  saveEventSettings: 'שמור הגדרות אירוע',
  guestExperience: 'חוויית המוזמן',
  rsvpQuestion: 'תגיעו לחגוג איתנו?',
  approveArrival: 'מאשר הגעה',
  declineArrival: 'לא אוכל להגיע',
  adults: 'מבוגרים',
  children: 'ילדים',
  notes: 'הערות',
  sendRsvp: 'שלח אישור',
  rsvpMaxAllowed: 'ניתן לאשר עד {maxAllowed} מוזמנים בהזמנה הזו.',
  rsvpTooManyGuests: 'בהזמנה הזו ניתן לאשר עד {maxAllowed} מוזמנים. יש להפחית מבוגרים או ילדים.',
  loadingInvitation: 'טוענים את ההזמנה שלך...',
  loading: 'טוענים...',
  invitationNotFound: 'ההזמנה לא נמצאה',
  openWaze: 'פתח Waze',
  addToGoogleCalendar: 'הוסף ליומן Google',
  sendGift: 'שליחת מתנה ב-Bit',
  contactHost: 'יצירת קשר עם בעל האירוע',
  googleConnection: 'חיבור Google',
  connectGoogle: 'חבר Google',
  googleDescription: 'חיבור Google ישמש ליומן, סנכרון אירועים ובהמשך ייבוא אנשי קשר באישור מפורש.',
  phoneContacts: 'אנשי קשר מ-Google',
  requestContacts: 'חבר אנשי קשר מ-Google',
  contactsDescription: 'אנשי הקשר יגיעו דרך Google באישור מפורש של בעל האירוע, ולא דרך WhatsApp.',
  eventCreated: 'האירוע נוצר',
  eventCreatedMessage: 'האירוע נוצר ונבחר כאירוע הפעיל. עכשיו אפשר להוסיף מוזמנים, לערוך הזמנה ולחבר WhatsApp.',
  draftSaved: 'הטיוטה נשמרה',
  draftSavedMessage: 'טיוטת ההזמנה נשמרה במסך הזה. מומלץ לבדוק את תצוגת המוזמן לפני שליחה.',
  settingsSaved: 'ההגדרות נשמרו',
  settingsSavedMessage: 'הגדרות האירוע עודכנו. בדוק Waze, Bit וטלפון לפני שליחת הזמנות.',
  integrationComingSoon: 'החיבור הזה מוכן מבחינת ממשק ויחובר לשרת בשלב הבא.',
  actionNeeded: 'נדרשת פעולה',
  missingHostId: 'צריך מזהה מנהל כדי לחבר WhatsApp.',
  actionFailed: 'הפעולה נכשלה',
  whatsappStarted: 'חיבור WhatsApp התחיל',
  whatsappStartedMessage: 'חיבור WhatsApp התחיל. אם נדרש QR, הוא יופיע כאן לסריקה.',
  whatsappReconnectRequired: 'צריך לחבר את WhatsApp מחדש.',
  whatsappReconnectRequiredHint: 'סרוק QR חדש ואז נסה לשלוח שוב.',
  qrRefreshStarted: 'מרענן QR',
  qrRefreshStartedMessage: 'בודקים קוד QR חדש. סרוק את הקוד העדכני שמופיע במסך.',
  whatsappDisconnected: 'WhatsApp נותק',
  whatsappDisconnectedMessage: 'WhatsApp נותק עבור האדמין הזה. אפשר לחבר אותו מחדש מהמסך הזה בכל רגע.',
  publicInviteLink: 'קישור הזמנה ציבורי',
  personalInviteLinks: 'קישורי הזמנה אישיים',
  personalInviteLinksDescription: 'כל מוזמן מקבל קישור פרטי משלו. הדוגמה כאן מציגה את המוזמן הראשון באירוע הפעיל.',
  noGuestInviteLink: 'צריך להוסיף מוזמנים כדי ליצור קישורי הזמנה אישיים.',
  copyLink: 'העתק קישור',
  openInvite: 'פתח הזמנה',
  linkCopied: 'הקישור הועתק',
  linkCopiedMessage: 'אפשר לשלוח אותו למוזמנים.',
  sendInvitations: 'שליחת הזמנות',
  googleContactsDescription: 'בחר נמענים מאנשי הקשר של Google, ואז WhatsApp ישלח הודעות אחת אחרי השנייה עם דיליי קטן.',
  googleConnected: 'Google מחובר',
  demoGoogleDisabledTitle: 'Google לא זמין בדמו',
  demoGoogleDisabledMessage: 'בדמו אנחנו לא פותחים הרשאת Google אמיתית ולא שומרים גישה לאנשי קשר. כדי לחבר Google צריך להיכנס עם משתמש אמיתי שאושר במערכת.',
  selectedContacts: 'נבחרו',
  searchGoogleContactsPlaceholder: 'חיפוש לפי שם או מספר טלפון',
  noGoogleContactsFound: 'לא נמצאו אנשי קשר שמתאימים לחיפוש',
  choose: 'בחר',
  fullName: 'שם מלא',
  phoneNumber: 'מספר טלפון',
  addContact: 'הוסף איש קשר',
  guest: 'מוזמן',
  messageToSend: 'הודעה לשליחה',
  defaultWhatsappMessage: 'היי {fullName}, זו ההזמנה שלך. נשמח לאישור הגעה דרך הקישור:',
  eventWhatsappSender: 'שליחה למוזמני האירוע',
  eventWhatsappSenderDescription: 'בחר מוזמנים, שלח לעצמך בדיקה, ואז הכנס את ההודעות לתור השליחה.',
  recipientFilter: 'סינון נמענים',
  pendingGuests: 'ממתינים',
  maybeGuests: 'אולי',
  allGuests: 'כולם',
  allowResend: 'אפשר שליחה חוזרת למוזמנים שכבר קיבלו הודעה',
  noRecipientsForFilter: 'אין מוזמנים שמתאימים לסינון הזה.',
  queueSelectedGuests: 'הכנס נבחרים לתור',
  sendTestToMyself: 'שלח בדיקה אליי',
  queueMessages: 'הכנס לתור שליחה',
  messagesQueued: 'הודעות נכנסו לתור',
  messagesQueuedMessage: 'הודעות נוספו לתור WhatsApp ויישלחו אחת אחרי השנייה עם דיליי.',
  missingTestPhone: 'צריך להגדיר מספר טלפון באירוע כדי לשלוח בדיקה.',
  testMessageSent: 'הודעת בדיקה נשלחה',
  testMessageSentMessage: 'בדוק את WhatsApp במכשיר לפני שליחה למוזמנים.',
  whatsappQueueMonitor: 'מעקב שליחה',
  whatsappQueueMonitorDescription: 'סטטוס חי לכל נמען, כולל שליחות שנכשלו וניסיונות חוזרים.',
  sent: 'נשלחו',
  failed: 'נכשלו',
  queued: 'בתור',
  skipped: 'דולגו',
  nextRecipient: 'הבא בתור',
  estimatedTimeLeft: 'זמן משוער שנותר',
  minutes: 'דקות',
  pauseSending: 'השהה שליחה',
  resumeSending: 'המשך שליחה',
  stopSending: 'עצור שליחה',
  retryFailedOnly: 'נסה שוב נכשלים בלבד',
  reason: 'סיבה',
  noQueueYet: 'אין כרגע תור שליחה פעיל.',
  sendHistory: 'היסטוריית שליחות',
  queueStatusIdle: 'אין תור פעיל',
  queueStatusRunning: 'שולח עכשיו',
  queueStatusPaused: 'מושהה',
  queueStatusStopping: 'עוצר',
  queueStatusDone: 'הסתיים',
  queueStatusFailed: 'נכשל',
  queueStatusCancelled: 'בוטל',
  queueItemQueued: 'ממתין בתור',
  queueItemSending: 'נשלח עכשיו',
  queueItemSent: 'נשלח',
  queueItemFailed: 'נכשל',
  queueItemSkipped: 'דולג',
  missingWhatsappMessage: 'ל-{count} נמענים אין WhatsApp. צריך ליצור איתם קשר טלפוני או לשלוח להם הזמנה במייל.',
  sendInvitationsByEmail: 'שלח הזמנות במייל',
  emailInvitationsSent: 'הזמנות במייל נשלחו',
  emailInvitationsSentMessage: '{sent} הזמנות נשלחו במייל.',
  emailInvitationsPartial: '{sent} מיילים נשלחו, {failed} נכשלו.',
  confirmWhatsappSendTitle: 'אישור שליחת WhatsApp',
  confirmWhatsappSendDescription: 'אתה עומד להכניס {count} הודעות לתור השליחה. הן יישלחו אחת אחרי השנייה עם דיליי קצר.',
  confirmWhatsappSend: 'אשר והכנס לתור',
  messagePreview: 'דוגמת הודעה',
  missingInviteLinksWarning: 'ל-{count} נמענים אין קישור אישי. כדאי להוסיף אותם כמוזמנים לפני השליחה.',
  contactAlreadySelectedTitle: 'איש הקשר כבר נמצא ברשימה',
  contactAlreadySelectedMessage: 'המספר הזה כבר נבחר או נוסף ידנית, לכן לא נוסיף אותו שוב.',
  phoneOrEmailRequired: 'צריך להזין לפחות מספר טלפון או כתובת מייל.',
  seating: 'הושבה',
  tableView: 'תצוגת שולחנות',
  genderView: 'תצוגת גברים / נשים',
  exportExcel: 'ייצוא לאקסל',
  noGenderSplit: 'ללא חלוקה',
  noGenderSplitGuests: 'לא נמצאו מוזמנים עם חלוקת גברים ונשים באירוע הזה.',
  tables: 'שולחנות',
  addTable: 'הוספת שולחן',
  tableName: 'שם שולחן',
  tableZone: 'אזור באולם',
  capacity: 'קיבולת',
  createTable: 'צור שולחן',
  chooseTable: 'בחר שולחן',
  seats: 'מקומות',
  seatsLeft: 'נותרו',
  seatsAssigned: 'מקומות שובצו',
  unassignedGuests: 'מוזמנים ללא הושבה',
  seatedGuests: 'מקומות משובצים',
  assignToTable: 'שייך לשולחן',
  remove: 'הסר',
  noSeatingGuests: 'עדיין אין מוזמנים בשולחן הזה.',
  allGuestsSeated: 'כל המוזמנים באירוע הזה שובצו.',
  generalZone: 'אזור כללי',
  guestsManagement: 'ניהול מוזמנים',
  sendReminder: 'שלח תזכורת',
  addGuest: 'הוסף מוזמן',
  edit: 'ערוך',
  editGuest: 'עריכת מוזמן',
  save: 'שמור',
  guestUpdated: 'המוזמן עודכן',
  guestDeleted: 'המוזמן הוסר',
  searchGuest: 'חיפוש מוזמן',
  searchGuestPlaceholder: 'שם, טלפון או מזהה הזמנה',
  guestSearchFound: 'נמצאו {count} מוזמנים שמתאימים לחיפוש',
  guestSearchNotFound: 'לא נמצא מוזמן מתאים באירוע הזה',
  guestSearchHint: 'אפשר לחפש לפי שם, מספר טלפון או מזהה ההזמנה האישי.',
  guestAlreadyInvitedTitle: 'המוזמן כבר קיים באירוע',
  guestAlreadyInvitedMessage: '{fullName} כבר הוזמן לאירוע הזה והסטטוס שלו הוא: {status}. אין צורך להזמין אותו שוב.',
  allStatuses: 'כל הסטטוסים',
  declined: 'לא מגיעים',
  reminded: 'קיבלו תזכורת',
  thanked: 'קיבלו תודה',
  maxAllowed: 'מקסימום מוזמנים',
  genderSplit: 'חלוקה',
  men: 'גברים',
  women: 'נשים',
  genderSplitTooHigh: 'כמות הגברים והנשים לא יכולה להיות גדולה ממקסימום המוזמנים להזמנה.',
  arriving: 'מגיעים',
  systemOverview: 'תמונת מצב',
  systemOverviewDescription: 'דשבורד סופר אדמין עם מבט מהיר על משתמשים, אירועים, מוזמנים וחיבורים פעילים בכל המערכת.',
  ownerDashboard: 'ניהול משתמשים',
  ownerDashboardDescription: 'אישור אדמינים, מעקב אחרי בעלי אירועים וצפייה באירועים שנוצרו במערכת.',
  systemUsers: 'משתמשים במערכת',
  activeEvents: 'אירועים פעילים',
  totalGuests: 'סה״כ מוזמנים',
  connectedWhatsapp: 'WhatsApp מחובר',
  approvedUsers: 'משתמשים מאושרים',
  approvedUsersRate: 'אחוז משתמשים מאושרים',
  whatsappConnectionRate: 'אחוז חיבורי WhatsApp',
  recentEvents: 'אירועים אחרונים במערכת',
  plan: 'מסלול',
  lastSeen: 'פעילות אחרונה',
  termsTitle: 'תקנון ותנאי שימוש',
  termsLegalNotice: 'הנוסח נועד להגן על בעל המערכת ועל מפעיליה, אך אינו מחליף ייעוץ משפטי פרטני. לפני שימוש מסחרי יש להעבירו לאישור עורך דין מוסמך.',
  termsIntro: 'תקנון זה מסדיר את השימוש במערכת אישרו? לניהול אירועים, מוזמנים, אישורי הגעה, הושבה, קישורי ניווט, מתנות ושליחת הודעות. שימוש במערכת מהווה הסכמה מלאה ובלתי מסויגת לתנאים.',
  termsEffectiveDate: 'תאריך תחולה: 16 ביוני 2026',
  termsDefinitionsTitle: 'הגדרות',
  termsDefinitionsOne: 'המערכת או השירות: אתר, אפליקציה, ממשקי ניהול, מסכי מוזמנים, חיבורים, אוטומציות וכל רכיב תוכנה המסופק תחת אישרו?.',
  termsDefinitionsTwo: 'בעל המערכת: מפעיל השירות, עובדיו, מנהליו, ספקיו, נציגיו וכל מי שפועל מטעמו.',
  termsDefinitionsThree: 'משתמש או בעל אירוע: כל אדם או גוף היוצר חשבון, מנהל אירוע, מעלה פרטי מוזמנים, שולח הודעות או משתמש בשירות בכל דרך.',
  termsUsageTitle: 'שימוש במערכת',
  termsUsageOne: 'המשתמש מתחייב להשתמש במערכת כדין, בתום לב, למטרות ניהול אירועים בלבד, ובהתאם לכל דין, לרבות דיני פרטיות, מאגרי מידע, תקשורת, ספאם וזכויות יוצרים.',
  termsUsageTwo: 'בעל האירוע אחראי באופן בלעדי לנכונות, חוקיות, מקור והרשאת השימוש בכל פרטי המוזמנים, אנשי הקשר, מספרי הטלפון, כתובות המייל, תמונות, טקסטים ותכנים שהועלו למערכת.',
  termsUsageThree: 'אין להשתמש במערכת לשליחת הודעות לא מורשות, הטרדה, התחזות, פגיעה בפרטיות, תכנים פוגעניים, פעילות מסחרית אסורה או כל פעולה העלולה לגרום נזק לבעל המערכת, לצד שלישי או לשירות.',
  termsUsageFour: 'בעל המערכת רשאי להגביל, לעכב, לחסום או למחוק שימוש, הודעות, חשבונות או נתונים אם קיים חשש להפרת תנאים, סיכון משפטי, עומס, שימוש חריג, תלונה או דרישה מצד צד שלישי.',
  termsAccountTitle: 'חשבון משתמש והרשאות',
  termsAccountOne: 'המשתמש אחראי לשמירת סודיות פרטי ההתחברות, לאבטחת המכשירים והחשבונות המחוברים ולכל פעולה שבוצעה מחשבונו, גם אם בוצעה על ידי אדם אחר.',
  termsAccountTwo: 'בעל המערכת רשאי לדרוש אימות, השלמת פרטים, אישור מנהל או אישור נוסף לפני פתיחת גישה, חיבור שירות חיצוני, שליחת הודעות או ביצוע פעולה רגישה.',
  termsAccountThree: 'מסירת פרטים שגויים, שימוש בזהות אחרת או ניסיון לעקוף הרשאות מהווים הפרה יסודית ויכולים להביא לחסימת החשבון ללא הודעה מוקדמת.',
  termsMessagingTitle: 'שליחת הודעות',
  termsMessagingOne: 'המשתמש מצהיר שקיבל את כל ההסכמות, ההרשאות והבסיסים החוקיים הנדרשים לשליחת הודעות, הזמנות, תזכורות ועדכונים לכל נמען.',
  termsMessagingTwo: 'המשתמש אחראי בלעדית לתוכן ההודעות, לניסוחן, לתדירות השליחה, לרשימת הנמענים, להסרת נמענים ולכל טענה של נמען או רשות מוסמכת בקשר להודעות.',
  termsMessagingThree: 'הודעות עשויות להישלח בהדרגה, להתעכב, להיכשל, להיחסם, להגיע לנמען שגוי או לא להגיע כלל בשל מגבלות WhatsApp, Google, ספקי תקשורת, מכשירים, חסימות, עומסים, טעויות משתמש או תקלות.',
  termsMessagingFour: 'בעל המערכת אינו צד לתוכן ההודעות ואינו מתחייב למסירה, קריאה, תגובה, זמינות, שמירת היסטוריה או התאמה למדיניות צדדים שלישיים.',
  termsPrivacyTitle: 'פרטיות',
  termsPrivacyOne: 'פרטי מוזמנים משמשים לניהול האירוע, אישורי הגעה, הושבה, תקשורת שאושרה על ידי בעל האירוע, תמיכה, אבטחה, תיעוד פעילות ושיפור השירות.',
  termsPrivacyTwo: 'בעל האירוע הוא האחראי לכך שמסירת המידע למערכת והשימוש בו מותרים לפי דין, וכי נמסרו לנמענים הודעות פרטיות או הסכמות ככל שנדרש.',
  termsPrivacyThree: 'המערכת עשויה לשמור לוגים, מזהים טכניים, קובצי Cookie, סטטוסי שליחה, תגובות מוזמנים ונתוני שימוש לצורכי אבטחה, תפעול, בקרה, פתרון תקלות והגנה משפטית.',
  termsPrivacyFour: 'בעל המערכת רשאי למחוק, לארכב או להגביל נתונים לפי שיקול דעתו, לפי דרישת המשתמש, לפי מגבלות תפעוליות או לפי חובה חוקית, ואינו אחראי לאובדן מידע שנגרם עקב גיבוי חסר, מחיקה, תקלה או שימוש שגוי.',
  termsThirdPartyTitle: 'שירותי צד שלישי',
  termsThirdPartyOne: 'השירות תלוי בשירותים חיצוניים כגון WhatsApp, Google, Waze, Bit, ספקי אירוח, דואר, SMS, דפדפנים ומכשירי קצה, ואינו שולט במדיניותם, זמינותם או פעולתם.',
  termsThirdPartyTwo: 'חיבור שירות חיצוני נעשה באחריות המשתמש בלבד ובכפוף לתנאי אותו שירות. שינוי במדיניות, חסימה, ניתוק, ביטול הרשאה או תקלה אצל צד שלישי אינם באחריות בעל המערכת.',
  termsThirdPartyThree: 'הצגת קישורים, מפות, ניווט, יומנים, אנשי קשר או אמצעי תשלום אינה מהווה המלצה, אחריות, אימות או התחייבות מצד בעל המערכת.',
  termsPaymentsTitle: 'מתנות, תשלומים וקישורי Bit',
  termsPaymentsOne: 'המערכת עשויה להציג קישורי מתנה או תשלום שנמסרו על ידי בעל האירוע. בעל המערכת אינו צד לעסקה, אינו מעבד תשלום ואינו אחראי להחזר, חיוב, שגיאה, תרמית או מחלוקת בין שולח המתנה לבעל האירוע.',
  termsPaymentsTwo: 'בעל האירוע אחראי לוודא שכל קישור תשלום, פרטי חשבון, פרסום או בקשה לכסף נכונים, חוקיים ושייכים לו.',
  termsContentTitle: 'תכנים וקניין רוחני',
  termsContentOne: 'כל זכויות הקניין הרוחני במערכת, בעיצוב, בקוד, בממשקים, במותג, בלוגיקה, בתבניות ובתיעוד שייכות לבעל המערכת או למורשיו.',
  termsContentTwo: 'המשתמש מעניק לבעל המערכת רישיון להשתמש בתכנים שהעלה ככל שנדרש להפעלת השירות, הצגתם למוזמנים, שליחתם, שמירתם, גיבוים, תמיכה טכנית והגנה משפטית.',
  termsContentThree: 'המשתמש מתחייב שלא להעלות תוכן מפר זכויות, מטעה, פוגעני, בלתי חוקי, ויראלי, מזיק או כזה הכולל מידע שאין לו הרשאה למסור.',
  termsAvailabilityTitle: 'זמינות, אבטחה ושינויים',
  termsAvailabilityOne: 'השירות מסופק כפי שהוא וכפי שיהיה זמין מעת לעת. אין התחייבות שהשירות יהיה רציף, מאובטח לחלוטין, נטול טעויות, מתאים לכל צורך או זמין בכל זמן.',
  termsAvailabilityTwo: 'בעל המערכת רשאי לשנות, להפסיק, לעדכן, למחוק, להגביל או לגבות תשלום עבור רכיבים בשירות בכל עת, בכפוף לדין, וללא אחריות לנזק עקיף שנובע מכך.',
  termsAvailabilityThree: 'המשתמש אחראי לבצע בדיקות לפני שליחת הזמנות, לוודא נכונות פרטי אירוע, קישורים, מספרים, טקסטים ותצוגות, ולשמור גיבוי של מידע חשוב מחוץ למערכת.',
  termsLiabilityTitle: 'אחריות',
  termsLiabilityOne: 'במידה המרבית המותרת בדין, בעל המערכת לא יישא באחריות לכל נזק ישיר, עקיף, מיוחד, תוצאתי, עונשי או עסקי, לרבות אובדן רווחים, פגיעה במוניטין, אובדן נתונים, שיבוש אירוע, אי הגעת מוזמנים או כשל בשליחת הודעות.',
  termsLiabilityTwo: 'בעל המערכת אינו אחראי לפעולות או מחדלים של משתמשים, מוזמנים, ספקי אירוע, שירותי צד שלישי, ספקי תקשורת, גוגל, וואטסאפ, וייז, ביט או כל גורם חיצוני.',
  termsLiabilityThree: 'אם חרף האמור תיקבע אחריות של בעל המערכת, היקף האחריות הכולל והמצטבר יוגבל לסכום ששולם בפועל על ידי המשתמש עבור השירות בשלושת החודשים שקדמו לאירוע המקנה עילה, או 100 ש״ח, לפי הנמוך.',
  termsLiabilityFour: 'המשתמש מאשר כי ללא מגבלות אחריות אלה בעל המערכת לא היה מספק את השירות או שהיה נדרש לתמחרו אחרת.',
  termsIndemnityTitle: 'שיפוי והגנה',
  termsIndemnityOne: 'המשתמש מתחייב לשפות, להגן ולפצות את בעל המערכת, עובדיו, מנהליו, ספקיו ונציגיו בגין כל דרישה, תביעה, נזק, קנס, הוצאה או שכר טרחת עורך דין הנובעים משימוש המשתמש, מהודעות שנשלחו, ממידע שהועלה או מהפרת התקנון או הדין.',
  termsIndemnityTwo: 'חובת השיפוי תחול גם ביחס לטענות מוזמנים, רשויות, ספקי צד שלישי, בעלי זכויות, משתמשים אחרים או כל גורם שנפגע לכאורה מפעולת המשתמש.',
  termsTerminationTitle: 'השעיה, מחיקה וסיום שימוש',
  termsTerminationOne: 'בעל המערכת רשאי להשעות או לסיים חשבון, למחוק נתונים או להגביל גישה במקרה של הפרה, חשש להפרה, חוב, סיכון אבטחה, דרישת רשות, תלונה או שימוש הפוגע בשירות.',
  termsTerminationTwo: 'המשתמש רשאי לבקש מחיקת חשבון ונתונים, בכפוף למידע שבעל המערכת רשאי או חייב לשמור לצורכי תיעוד, אבטחה, גבייה, עמידה בדין והגנה מפני תביעות.',
  termsTerminationThree: 'סיום השימוש אינו גורע מתוקף סעיפי אחריות, פרטיות, קניין רוחני, שיפוי, דין ושיפוט וכל סעיף שמטבעו נועד להמשיך לחול.',
  termsChangesTitle: 'עדכון התקנון',
  termsChangesOne: 'בעל המערכת רשאי לעדכן את התקנון מעת לעת. המשך שימוש לאחר עדכון מהווה הסכמה לנוסח המעודכן.',
  termsChangesTwo: 'במקרה של שינוי מהותי, ייתכן שהמערכת תדרוש אישור מחודש לפני המשך שימוש.',
  termsLawTitle: 'דין וסמכות שיפוט',
  termsLawOne: 'על התקנון והשימוש בשירות יחולו דיני מדינת ישראל בלבד, ללא תחולת כללי ברירת דין.',
  termsLawTwo: 'סמכות השיפוט הבלעדית בכל מחלוקת תהיה נתונה לבתי המשפט המוסמכים במחוז תל אביב-יפו, אלא אם הדין מחייב אחרת.',
  logout: 'יציאה',
  dangerZone: 'אזור מסוכן',
  deleteAccount: 'מחיקת כל נתוני המשתמש',
  deleteAccountDescription: 'הפעולה תמחק לצמיתות את המשתמש הנוכחי, כל האירועים שלו, המוזמנים, נתוני חיבור WhatsApp וכל הרשומות הקשורות.',
  deleteAccountConfirm: 'הפעולה תמחק לצמיתות את המשתמש הנוכחי ואת כל הנתונים הקשורים אליו. להמשיך?',
  deleteAccountPrompt: 'כתוב DELETE כדי לאשר מחיקה לצמיתות.',
  deleteCancelled: 'המחיקה בוטלה',
  deleteCancelledMessage: 'לא נמחקו נתונים.',
  accountDeleted: 'נתוני המשתמש נמחקו',
  deletedEvents: 'אירועים שנמחקו',
  deletedGuests: 'מוזמנים שנמחקו',
  cancel: 'ביטול',
  logoutTitle: 'לצאת מהמערכת?',
  logoutDescription: 'אתה עומד לצאת מממשק הניהול.',
  logoutDataNotice: 'הפעולה לא מוחקת אירועים, מוזמנים, הזמנות או הגדרות WhatsApp. אפשר להתחבר שוב בכל רגע.',
  deleteAccountModalTitle: 'למחוק את המשתמש לצמיתות?',
  maybeArrival: 'אולי',
  maybe: 'אולי',
  rsvpThanksTitle: 'תודה, האישור נשמר',
  rsvpConfirmedThanks: 'מעולה, עדכנו את בעל האירוע שאתם מגיעים. נתראה בשמחה באירוע.',
  rsvpMaybeThanks: 'אין בעיה, שמרנו את התשובה כאולי. אפשר לעדכן בהמשך אם משהו משתנה.',
  rsvpDeclinedThanks: 'תודה שעדכנתם את בעל האירוע. התשובה נשמרה.',
  editRsvp: 'עריכת תשובה',
  inviteId: 'מזהה הזמנה',
  reminderDescription: 'בחר למי לשלוח תזכורת. ההודעות ייכנסו לתור WhatsApp ויישלחו אחת אחרי השנייה עם דיליי.',
  reminderAudience: 'קהל יעד לתזכורת',
  reminderAudienceAwaiting: 'מי שלא ענה או סימן אולי',
  reminderAudienceConfirmed: 'מי שאישר הגעה',
  reminderAudienceAll: 'כולם: אישרו, אולי ולא ענו',
  recommendedReminderPlan: 'תזמון מומלץ',
  reminderPlanNoDate: 'כדי לקבל המלצת תזמון צריך להגדיר תאריך לאירוע.',
  reminderPlanPastEvent: 'האירוע כבר עבר, לכן אין המלצת תזכורת אוטומטית.',
  reminderPlanFinalWindow: 'נותרו {days} ימים לאירוע. זה חלון אחרון לתזכורת קצרה וממוקדת.',
  reminderPlanCadence: 'נותרו {days} ימים לאירוע. מומלץ לתזכר כל כמה ימים, ולהפסיק תזכורות כלליות שלושה ימים לפני האירוע.',
  reminderRecipients: 'מוזמנים יקבלו קישור אישי להזמנה',
  defaultReminderMessage: 'היי {fullName}, תזכורת קטנה לאשר הגעה לאירוע בקישור האישי שלך: {inviteLink}',
  defaultConfirmedReminderMessage: 'היי {fullName}, תזכורת קטנה לאירוע שמתקרב. כל הפרטים והקישור האישי שלך כאן: {inviteLink}',
  pendingApprovalMessage: 'בקשת האדמין נשלחה לסופר אדמין. אחרי אישור תקבל מייל ואז תוכל להתחבר.',
  pendingApproval: 'ממתינים לאישור',
  approveAdmin: 'אשר אדמין',
  adminApproved: 'האדמין אושר',
  adminApprovedMessage: 'המשתמש אושר, קיבל מייל, ויכול עכשיו להתחבר לניהול אירועים.',
  actions: 'פעולות',
  PENDING_APPROVAL: 'ממתין לאישור',
  APPROVED: 'מאושר',
  SUSPENDED: 'מושהה',
  googleDisconnected: 'Google נותק',
  googleDisconnectedMessage: 'חיבור Google הוסר מהחשבון. אנשי קשר לא ייטענו עד חיבור מחדש.',
  googleNotConfigured: 'חיבור Google עדיין לא מוגדר.',
  googleNotConfiguredHint: 'צריך להגדיר GOOGLE_CLIENT_ID ו-GOOGLE_CLIENT_SECRET בקובץ backend/.env וליצור OAuth Client ב-Google Cloud.',
  connectedAs: 'מחובר כ',
  reconnectGoogle: 'חבר Google מחדש',
  disconnectGoogle: 'נתק Google',
  openGoogleContacts: 'השתמש באנשי קשר מ-Google ב-WhatsApp',
  invalidEventName: 'שם האירוע חייב להכיל 2-160 אותיות או מספרים.',
  invalidDate: 'בחר תאריך תקין.',
  invalidVenue: 'שם המקום חייב להכיל 2-160 אותיות או מספרים.',
  invalidPhone: 'יש להזין מספר טלפון ישראלי תקין, למשל 050-000-0000.',
  invalidGuestCount: 'יש להזין מספר חיובי.',
  helpCenter: 'מרכז עזרה',
  helpIntro: 'תשובות מהירות לתהליכים המרכזיים במערכת.',
  startSystemTour: 'פתח סיור במערכת',
  faqCreateEventQuestion: 'איך יוצרים אירוע חדש?',
  faqCreateEventAnswer: 'נכנסים למסך אירועים, לוחצים על אירוע חדש, וממלאים שם אירוע, תאריך, מקום, כתובת, טלפון וכמות מוזמנים משוערת. הכתובת תשמש אותנו לפתיחת ניווט ב-Waze.',
  faqGuestLoginQuestion: 'האם מוזמן צריך להתחבר למערכת?',
  faqGuestLoginAnswer: 'לא. כל מוזמן מקבל קישור אישי להזמנה ויכול לאשר הגעה, לסרב או לבחור אולי בלי לפתוח חשבון.',
  faqInviteIdQuestion: 'איך יודעים מי אישר הגעה?',
  faqInviteIdAnswer: 'לכל מוזמן יש מזהה הזמנה אישי. הקישור שנשלח אליו ייחודי, ולכן התשובה נשמרת על המוזמן הנכון.',
  faqWhatsappQuestion: 'איך עובד החיבור ל-WhatsApp?',
  faqWhatsappAnswer: 'בעל האירוע מחבר את חשבון ה-WhatsApp שלו דרך מסך WhatsApp. החיבור נשמר לחשבון שלו, והודעות נשלחות אחת אחרי השנייה עם דיליי קטן.',
  faqGoogleQuestion: 'איך עובדים אנשי קשר מגוגל?',
  faqGoogleAnswer: 'כפתור Google פותח הרשאה של Google. אחרי אישור, אנשי הקשר נטענים מגוגל ובעל האירוע בוחר למי לשלוח ולמי לא.',
  faqApprovalQuestion: 'למה אדמין לא מצליח להתחבר?',
  faqApprovalAnswer: 'אדמין חדש ממתין לאישור של הסופר אדמין. אחרי האישור הוא יוכל להתחבר ולנהל אירועים משלו.',
  faqDemoQuestion: 'מה קורה במצב דמו?',
  faqDemoAnswer: 'בדמו יש אירוע אחד לדוגמה ואפשר להתנסות בתהליך בלי לשמור נתונים ל-DB.',
  faqOwnerQuestion: 'מה הסופר אדמין יכול לראות?',
  faqOwnerAnswer: 'הסופר אדמין יכול לעקוב אחרי משתמשים ואירועים במערכת, אבל לא יכול לגשת או להפעיל את ה-WhatsApp של המשתמשים.',
  completeProfileTitle: 'השלמת פרטי משתמש',
  completeProfileDescription: 'לפני שממשיכים, צריך לעדכן שם מלא ומספר טלפון כדי שהחשבון יהיה ברור ומוכן לניהול אירועים.',
  editProfileTitle: 'פרטי משתמש',
  editProfileDescription: 'כאן אפשר לעדכן את פרטי האדמין. אלה פרטים של המשתמש במערכת, לא של אירוע ספציפי.',
  saveProfile: 'שמור פרטים',
  profileSaved: 'הפרטים נשמרו',
  profileSavedMessage: 'פרטי המשתמש עודכנו. השם העליון במערכת משתמש עכשיו בשם המלא שנשמר.',
  invalidEmail: 'יש להזין כתובת אימייל תקינה.',
  invalidFullName: 'יש להזין שם מלא באורך 2-80 אותיות.',
  termsConsentTitle: 'אישור תקנון',
  termsConsentIntro: 'יש לקרוא את התקנון לפני שימוש במערכת. האישור נשמר בקוקי לפי המשתמש הזה.',
  termsReadAndAccepted: 'קראתי את התקנון ואני מאשר שימוש במערכת.',
  termsScrollToApprove: 'יש לגלול את התקנון כדי לאפשר אישור.',
  confirmApproval: 'קראתי ואני מאשר',
  invalidCredentials: 'האימייל או הסיסמה לא נכונים.',
  invalidCredentialsHint: 'בדוק את הפרטים ונסה שוב.',
  waitingApprovalError: 'חשבון האדמין עדיין ממתין לאישור של הסופר אדמין.',
  waitingApprovalHint: 'אחרי האישור תקבל הודעה במייל.',
  emailAlreadyUsed: 'האימייל הזה כבר מחובר לחשבון אדמין אחר.',
  emailAlreadyUsedHint: 'השתמש באימייל אחר או התחבר לחשבון הקיים.',
  networkError: 'לא הצלחנו להתחבר לשרת. בדוק שהבאקנד רץ ונסה שוב.',
  networkErrorHint: 'אם זה ממשיך, בדוק את כתובת ה-API בקובץ הסביבה.',
  sessionExpired: 'החיבור שלך פג. צריך להתחבר מחדש.',
  sessionExpiredHint: 'זה שומר על החשבון שלך מחיבורים ישנים.',
  genericError: 'משהו השתבש. נסה שוב בעוד רגע.',
  genericErrorHint: 'הפעולה לא הושלמה.',
  permissionDenied: 'אין לך הרשאה לבצע את הפעולה הזאת.',
  permissionDeniedHint: 'בקש מהסופר אדמין לאשר את הגישה המתאימה.',
  notFoundError: 'הפריט שביקשת לא נמצא.',
  notFoundHint: 'רענן את המסך ונסה שוב.',
  validationError: 'חלק מהפרטים לא תקינים.',
  validationErrorHint: 'בדוק את השדות המסומנים ותקן אותם.',
  systemLogs: 'לוגים מערכתיים',
  systemLogsDescription: 'לוגים מובנים של הבאקנד והפרונט עם פילטרים, מוכנים לחשיבה בסגנון Elastic.',
  refreshLogs: 'רענן לוגים',
  logLevel: 'רמה',
  logSource: 'מקור',
  logCategory: 'קטגוריה',
  requestId: 'מזהה בקשה',
  requestPath: 'הבקשה עצמה',
  requestStatus: 'סטטוס',
  requestType: 'סוג הבקשה',
  message: 'הודעה',
  applyFilters: 'הפעל פילטרים',
  profileValidationBlocked: 'חלק מפרטי המשתמש חסרים או לא תקינים. תקן את השדות למעלה כדי להמשיך.',
  cookieConsentTitle: 'קוקיס ואחסון מקומי',
  cookieConsentDescription: 'אנחנו משתמשים בקוקיס ובאחסון מקומי כדי לזכור אישורים, מצב התחברות, שפה והעדפות חיוניות של המערכת.',
  cookieConsentAccept: 'מאשר קוקיס',
  onboardingTitle: 'סיור קצר במערכת',
  onboardingDescription: 'נכיר בכמה צעדים את הפעולות המרכזיות שיעזרו לך להקים אירוע, להזמין מוזמנים ולקבל אישורי הגעה.',
  onboardingSavedHint: 'הבחירה תישמר לחשבון שלך',
  onboardingCompletedTitle: 'הסיור הושלם',
  onboardingCompletedMessage: 'מעולה, שמרנו שסיימת את הכרת המערכת. אפשר להמשיך לעבוד רגיל.',
  onboardingSkippedTitle: 'דילגת על הסיור',
  onboardingSkippedMessage: 'אין בעיה, אפשר לפתוח את הכרת המערכת שוב מסימן העזרה.',
  onboardingEventsTitle: 'יצירת אירוע',
  onboardingEventsText: 'כאן יוצרים אירוע חדש, בוחרים תאריך, מקום, כתובת, טלפון ונושא עיצוב. זה הבסיס לכל ההזמנות והמוזמנים.',
  onboardingGuestsTitle: 'ניהול מוזמנים',
  onboardingGuestsText: 'כאן מוסיפים מוזמנים, רואים סטטוס אישור הגעה, מזהה הזמנה אישי וכמות מוזמנים מותרת לכל משפחה.',
  onboardingInvitationsTitle: 'עיצוב ונוסח הזמנה',
  onboardingInvitationsText: 'כאן בוחרים נושא אירוע, עורכים את הטקסט, רואים תצוגה מקדימה ושומרים נוסח מותאם לאירוע.',
  onboardingWhatsappTitle: 'שליחת הודעות',
  onboardingWhatsappText: 'כאן מחברים WhatsApp, בוחרים אנשי קשר מ-Google או מוסיפים ידנית, ושולחים הודעות אחת אחרי השנייה עם דיליי.',
  onboardingSeatingTitle: 'הושבת אורחים',
  onboardingSeatingText: 'כאן יוצרים שולחנות, מגדירים קיבולת ומשייכים מוזמנים שאישרו כדי לקבל תמונת הושבה מסודרת.',
  skipOnboarding: 'דלג על הסיור',
  finishOnboarding: 'סיימתי',
  openFeature: 'פתח את הפיצ׳ר',
  next: 'הבא',
  back: 'חזור',
} as const;
