export const en = {
  appName: 'Ishru?',
  workspace: 'Event management',
  hostId: 'Host ID',
  hostIdPlaceholder: 'Admin ObjectId',
  events: 'Events',
  whatsapp: 'WhatsApp',
  invitations: 'Invitations',
  guestView: 'Guest view',
  settings: 'Settings',
  createEvent: 'New event',
  createEventFlow: 'Create new event',
  eventName: 'Event name',
  eventNamePlaceholder: 'Example: Ariel ceremony',
  venuePlaceholder: 'Example: Oranim Hall',
  addressPlaceholder: 'Example: 10 Herzl St, Herzliya',
  expectedGuests: 'Expected guests',
  search: 'Search events',
  guests: 'Guests',
  confirmed: 'Confirmed',
  pending: 'Pending',
  eventDate: 'Date',
  venue: 'Venue',
  address: 'Address',
  wazeLink: 'Waze link',
  noEvents: 'No events yet',
  connectWhatsapp: 'WhatsApp connection',
  connect: 'Connect',
  disconnect: 'Disconnect',
  refreshQr: 'Refresh QR',
  status: 'Status',
  scanQr: 'Scan this code from the mobile app',
  disconnected: 'Disconnected',
  qrReady: 'QR ready',
  connected: 'Connected',
  apiHint: 'This interface is ready for the local API.',
  selectedEvent: 'Active event',
  activeEvent: 'Active event',
  rsvpProgress: 'RSVP progress',
  editInvitation: 'Edit invitation',
  previewGuest: 'Guest view',
  setupEvent: 'Event setup',
  openWhatsapp: 'WhatsApp',
  chooseEvent: 'Choose event',
  invitationStudio: 'Invitation design and copy',
  eventTheme: 'Event theme',
  separateSeatingEvent: 'Separate seating event',
  separateSeatingEventDescription: 'Mark how many men and women are in each invitation to make seating easier.',
  invitationText: 'Invitation text',
  invitationTitle: 'Title',
  template: 'Template',
  saveDraft: 'Save draft',
  preview: 'Preview',
  brit: 'Brit',
  wedding: 'Wedding',
  bar_mitzvah: 'Bar mitzvah',
  birthday: 'Birthday',
  corporate: 'Corporate',
  classic: 'Classic',
  warm: 'Warm',
  elegant: 'Elegant',
  casual: 'Casual',
  authTitle: 'Sign in',
  authSubtitle: 'Manage events, invitations, and WhatsApp',
  email: 'Email',
  password: 'Password',
  forgotPassword: 'Forgot password',
  emailRequiredForReset: 'Enter your email to send a password reset link.',
  passwordResetEmailSentTitle: 'Reset email sent',
  passwordResetEmailSent: 'If the account exists, a link for creating a new password was sent.',
  createNewPassword: 'Create a new password',
  createNewPasswordDescription: 'Choose a strong password to sign back into the system.',
  currentPassword: 'Current password',
  newPassword: 'New password',
  saveNewPassword: 'Save new password',
  changePassword: 'Change password',
  updatePassword: 'Update password',
  passwordUpdated: 'Password updated',
  passwordUpdatedMessage: 'Use the new password next time you sign in.',
  passwordTooWeak: 'Password is not strong enough. Complete all strength rules before continuing.',
  passwordRequired: 'Enter a password.',
  passwordWeak: 'Weak password',
  passwordMedium: 'Medium password',
  passwordStrong: 'Strong password',
  passwordMissingRules: 'Missing',
  passwordRuleLength: 'at least 10 characters',
  passwordRuleLowercase: 'lowercase letter',
  passwordRuleUppercase: 'uppercase letter',
  passwordRuleNumber: 'number',
  passwordRuleSpecial: 'special character',
  login: 'Login',
  register: 'Register',
  demoLogin: 'Enter demo',
  pendingApprovalMessage: 'Your admin request was sent to the super admin. You will receive an email after approval, then you can sign in.',
  eventSettings: 'Event settings',
  eventPhone: 'Event phone number',
  bitLink: 'Bit gift link',
  saveEventSettings: 'Save event settings',
  guestExperience: 'Guest experience',
  rsvpQuestion: 'Will you join us?',
  approveArrival: 'Confirm arrival',
  maybeArrival: 'Maybe',
  declineArrival: 'Cannot attend',
  adults: 'Adults',
  children: 'Children',
  notes: 'Notes',
  sendRsvp: 'Send RSVP',
  rsvpMaxAllowed: 'This invitation allows up to {maxAllowed} guests.',
  rsvpTooManyGuests: 'This invitation allows up to {maxAllowed} guests. Reduce the number of adults or children.',
  loadingInvitation: 'Loading your invitation...',
  loading: 'Loading...',
  invitationNotFound: 'Invitation not found',
  rsvpThanksTitle: 'Thank you, your response was saved',
  rsvpConfirmedThanks: 'Great, we updated the host that you are coming. See you at the event.',
  rsvpMaybeThanks: 'No problem, we saved your response as maybe. You can update it later if things change.',
  rsvpDeclinedThanks: 'Thank you for letting the host know. Your response was saved.',
  editRsvp: 'Edit response',
  openWaze: 'Open Waze',
  addToGoogleCalendar: 'Add to Google Calendar',
  sendGift: 'Send Bit gift',
  contactHost: 'Contact host',
  googleConnection: 'Google connection',
  connectGoogle: 'Connect Google',
  googleDescription: 'Google will support calendar sync, event creation, and contact import after explicit approval.',
  phoneContacts: 'Google contacts',
  requestContacts: 'Connect Google contacts',
  contactsDescription: 'Contacts will come from Google after explicit host approval, not from WhatsApp.',
  eventCreated: 'Event created',
  eventCreatedMessage: 'The event was created and selected as active. You can now add guests, edit the invitation, and connect WhatsApp.',
  draftSaved: 'Draft saved',
  draftSavedMessage: 'The invitation draft was saved on this screen. Review the guest preview before sending it.',
  settingsSaved: 'Settings saved',
  settingsSavedMessage: 'The event settings were updated. Check Waze, Bit, and phone details before sending invitations.',
  integrationComingSoon: 'This integration is ready in the UI and will be connected to the server next.',
  actionNeeded: 'Action needed',
  missingHostId: 'A host ID is required to connect WhatsApp.',
  actionFailed: 'Action failed',
  whatsappStarted: 'WhatsApp connection started',
  whatsappStartedMessage: 'WhatsApp connection started. If a QR code is needed, it will appear here for scanning.',
  qrRefreshStarted: 'Refreshing QR',
  qrRefreshStartedMessage: 'Checking for a fresh QR code. Scan the newest code shown on this screen.',
  whatsappDisconnected: 'WhatsApp disconnected',
  whatsappDisconnectedMessage: 'WhatsApp was disconnected for this admin. You can reconnect it from this screen anytime.',
  publicInviteLink: 'Public invite link',
  personalInviteLinks: 'Personal invite links',
  personalInviteLinksDescription: 'Every guest gets a private link. The example below uses the first guest in the active event.',
  noGuestInviteLink: 'Add guests to generate personal invitation links.',
  copyLink: 'Copy link',
  openInvite: 'Open invite',
  linkCopied: 'Link copied',
  linkCopiedMessage: 'You can now send it to guests.',
  sendInvitations: 'Send invitations',
  googleContactsDescription: 'Choose recipients from Google Contacts, then WhatsApp will send messages one by one with a small delay.',
  googleConnected: 'Google connected',
  demoGoogleDisabledTitle: 'Google is disabled in demo',
  demoGoogleDisabledMessage: 'Demo mode does not open a real Google authorization flow or store contact access. Sign in with an approved real user to connect Google.',
  googleDisconnected: 'Google disconnected',
  googleDisconnectedMessage: 'The Google connection was removed from this account. Contacts will not load until Google is reconnected.',
  googleNotConfigured: 'Google connection is not configured yet.',
  googleNotConfiguredHint: 'Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in backend/.env and create an OAuth Client in Google Cloud.',
  connectedAs: 'Connected as',
  reconnectGoogle: 'Reconnect Google',
  disconnectGoogle: 'Disconnect Google',
  openGoogleContacts: 'Use Google contacts in WhatsApp',
  selectedContacts: 'selected',
  searchGoogleContactsPlaceholder: 'Search by name or phone number',
  noGoogleContactsFound: 'No matching contacts were found',
  choose: 'Choose',
  fullName: 'Full name',
  inviteId: 'Invite ID',
  phoneNumber: 'Phone number',
  addContact: 'Add contact',
  guest: 'Guest',
  messageToSend: 'Message to send',
  defaultWhatsappMessage: 'Hi {fullName}, here is your invitation. Please confirm arrival through the link:',
  queueMessages: 'Queue messages',
  messagesQueued: 'Messages queued',
  messagesQueuedMessage: 'messages were added to the WhatsApp queue and will be sent one by one with a delay.',
  missingWhatsappMessage: '{count} recipients do not have WhatsApp. Contact them by phone or send the invitation by email.',
  sendInvitationsByEmail: 'Send invitations by email',
  emailInvitationsSent: 'Email invitations sent',
  emailInvitationsSentMessage: '{sent} invitations were sent by email.',
  emailInvitationsPartial: '{sent} emails were sent, {failed} failed.',
  confirmWhatsappSendTitle: 'Confirm WhatsApp send',
  confirmWhatsappSendDescription: 'You are about to add {count} messages to the send queue. They will be sent one by one with a short delay.',
  confirmWhatsappSend: 'Confirm and queue',
  messagePreview: 'Message preview',
  missingInviteLinksWarning: '{count} recipients do not have a personal invite link. Add them as guests before sending.',
  contactAlreadySelectedTitle: 'Contact already listed',
  contactAlreadySelectedMessage: 'This phone number is already selected or was added manually, so it was not added again.',
  phoneOrEmailRequired: 'Enter at least a phone number or an email address.',
  seating: 'Seating',
  tableView: 'Tables view',
  genderView: 'Men / women view',
  exportExcel: 'Export to Excel',
  noGenderSplit: 'No split set',
  noGenderSplitGuests: 'No guests with men/women split were found for this event.',
  tables: 'Tables',
  addTable: 'Add table',
  tableName: 'Table name',
  tableZone: 'Area',
  capacity: 'Capacity',
  createTable: 'Create table',
  chooseTable: 'Choose table',
  seats: 'seats',
  seatsLeft: 'left',
  seatsAssigned: 'seats assigned',
  unassignedGuests: 'Unassigned guests',
  seatedGuests: 'Seated guests',
  assignToTable: 'Assign to table',
  remove: 'Remove',
  noSeatingGuests: 'No guests are seated here yet.',
  allGuestsSeated: 'All guests for this event are seated.',
  generalZone: 'General area',
  guestsManagement: 'Guest management',
  sendReminder: 'Send reminder',
  reminderDescription: 'This will queue WhatsApp reminders for guests who are still pending or marked as maybe.',
  reminderAudience: 'Reminder audience',
  reminderAudienceAwaiting: 'No response or maybe',
  reminderAudienceConfirmed: 'Confirmed guests',
  reminderAudienceAll: 'All: confirmed, maybe, and no response',
  recommendedReminderPlan: 'Recommended timing',
  reminderPlanNoDate: 'Set an event date to get a reminder timing recommendation.',
  reminderPlanPastEvent: 'This event has already passed, so no automatic reminder recommendation is shown.',
  reminderPlanFinalWindow: 'There are {days} days until the event. This is the final window for a short focused reminder.',
  reminderPlanCadence: 'There are {days} days until the event. A good cadence is every few days, stopping broad reminders three days before the event.',
  reminderRecipients: 'Guests will receive a personal invite link',
  defaultReminderMessage: 'Hi {fullName}, a quick reminder to confirm arrival for the event here: {inviteLink}',
  defaultConfirmedReminderMessage: 'Hi {fullName}, a quick reminder for the upcoming event. Your personal details and link are here: {inviteLink}',
  addGuest: 'Add guest',
  edit: 'Edit',
  editGuest: 'Edit guest',
  save: 'Save',
  guestUpdated: 'Guest updated',
  guestDeleted: 'Guest removed',
  searchGuest: 'Search guest',
  searchGuestPlaceholder: 'Name, phone, or invite ID',
  guestSearchFound: 'Found {count} matching guests',
  guestSearchNotFound: 'No matching guest was found in this event',
  guestSearchHint: 'Search by name, phone number, or personal invite ID.',
  guestAlreadyInvitedTitle: 'Guest already exists in this event',
  guestAlreadyInvitedMessage: '{fullName} was already invited to this event and their status is: {status}. There is no need to invite them again.',
  allStatuses: 'All statuses',
  declined: 'Declined',
  maybe: 'Maybe',
  reminded: 'Reminded',
  thanked: 'Thanked',
  maxAllowed: 'Max allowed',
  genderSplit: 'Split',
  men: 'Men',
  women: 'Women',
  genderSplitTooHigh: 'Men and women count cannot be higher than the max allowed guests for this invitation.',
  arriving: 'Arriving',
  systemOverview: 'System overview',
  systemOverviewDescription: 'Super admin dashboard with a quick view of users, events, guests, and active connections across the system.',
  ownerDashboard: 'User management',
  ownerDashboardDescription: 'Approve admins, track event hosts, and review events created in the system.',
  systemUsers: 'System users',
  pendingApproval: 'Pending approval',
  approveAdmin: 'Approve admin',
  adminApproved: 'Admin approved',
  adminApprovedMessage: 'This user was approved, received an email, and can now sign in to manage events.',
  actions: 'Actions',
  PENDING_APPROVAL: 'Pending approval',
  APPROVED: 'Approved',
  SUSPENDED: 'Suspended',
  activeEvents: 'Active events',
  totalGuests: 'Total guests',
  connectedWhatsapp: 'Connected WhatsApp',
  approvedUsers: 'approved users',
  approvedUsersRate: 'Approved users rate',
  whatsappConnectionRate: 'WhatsApp connection rate',
  recentEvents: 'Recent system events',
  plan: 'Plan',
  lastSeen: 'Last seen',
  termsTitle: 'Terms of Use',
  termsLegalNotice: 'This text is designed to protect the system owner and operators, but it does not replace tailored legal advice. Have it reviewed by a qualified lawyer before commercial launch.',
  termsIntro: 'These terms govern use of the Ishru? system for managing events, guests, RSVPs, seating, navigation links, gifts, and messaging. Using the system means full acceptance of these terms.',
  termsEffectiveDate: 'Effective date: June 16, 2026',
  termsDefinitionsTitle: 'Definitions',
  termsDefinitionsOne: 'System or service means the site, app, admin interfaces, guest screens, integrations, automations, and any software component provided under Ishru?.',
  termsDefinitionsTwo: 'System owner means the service operator, its employees, managers, suppliers, representatives, and anyone acting on its behalf.',
  termsDefinitionsThree: 'User or host means any person or entity that opens an account, manages an event, uploads guest details, sends messages, or uses the service in any way.',
  termsUsageTitle: 'Use of the platform',
  termsUsageOne: 'The user must use the system lawfully, in good faith, for event management purposes only, and according to all applicable privacy, database, communications, anti-spam, and copyright laws.',
  termsUsageTwo: 'The host is solely responsible for the accuracy, legality, source, and authorization for every guest detail, contact, phone number, email address, image, text, and item uploaded to the system.',
  termsUsageThree: 'The system may not be used for unauthorized messages, harassment, impersonation, privacy violations, offensive content, prohibited commercial activity, or any action that may harm the system owner, a third party, or the service.',
  termsUsageFour: 'The system owner may limit, delay, block, or delete usage, messages, accounts, or data when there is concern about a breach, legal risk, load, abnormal use, complaint, or third-party request.',
  termsAccountTitle: 'User account and permissions',
  termsAccountOne: 'The user is responsible for keeping login details confidential, securing connected devices and accounts, and every action performed through the account, even if performed by someone else.',
  termsAccountTwo: 'The system owner may require verification, profile completion, admin approval, or additional approval before granting access, connecting an external service, sending messages, or performing a sensitive action.',
  termsAccountThree: 'Providing false details, using another identity, or trying to bypass permissions is a material breach and may lead to account blocking without prior notice.',
  termsMessagingTitle: 'Messaging',
  termsMessagingOne: 'The user represents that all required consents, permissions, and lawful bases were obtained before sending messages, invitations, reminders, or updates to any recipient.',
  termsMessagingTwo: 'The user is solely responsible for message content, wording, send frequency, recipient lists, recipient removal, and any claim by a recipient or authority relating to messages.',
  termsMessagingThree: 'Messages may be sent gradually, delayed, fail, be blocked, reach the wrong recipient, or not arrive at all due to WhatsApp, Google, carriers, devices, blocks, load, user mistakes, or outages.',
  termsMessagingFour: 'The system owner is not a party to message content and does not guarantee delivery, reading, response, availability, history retention, or compliance with third-party policies.',
  termsPrivacyTitle: 'Privacy',
  termsPrivacyOne: 'Guest data is used for event management, RSVP tracking, seating, host-approved communication, support, security, activity records, and service improvement.',
  termsPrivacyTwo: 'The host is responsible for ensuring that providing data to the system and using it is lawful, and that privacy notices or consents were provided where required.',
  termsPrivacyThree: 'The system may store logs, technical identifiers, cookies, sending statuses, guest responses, and usage data for security, operations, auditing, troubleshooting, and legal protection.',
  termsPrivacyFour: 'The system owner may delete, archive, or restrict data at its discretion, at the user request, due to operational limits, or due to legal duties, and is not responsible for data loss caused by missing backups, deletion, outage, or incorrect use.',
  termsThirdPartyTitle: 'Third-party services',
  termsThirdPartyOne: 'The service depends on external services such as WhatsApp, Google, Waze, Bit, hosting providers, email, SMS, browsers, and endpoint devices, and does not control their policies, availability, or operation.',
  termsThirdPartyTwo: 'Connecting an external service is the user responsibility and is subject to that service terms. Policy changes, blocking, disconnection, revoked authorization, or third-party failures are not the system owner responsibility.',
  termsThirdPartyThree: 'Displaying links, maps, navigation, calendars, contacts, or payment methods is not a recommendation, warranty, verification, or commitment by the system owner.',
  termsPaymentsTitle: 'Gifts, payments, and Bit links',
  termsPaymentsOne: 'The system may display gift or payment links provided by the host. The system owner is not a party to the transaction, does not process payments, and is not responsible for refunds, charges, errors, fraud, or disputes between the gift sender and the host.',
  termsPaymentsTwo: 'The host is responsible for verifying that every payment link, account detail, publication, or money request is accurate, lawful, and belongs to the host.',
  termsContentTitle: 'Content and intellectual property',
  termsContentOne: 'All intellectual property rights in the system, design, code, interfaces, brand, logic, templates, and documentation belong to the system owner or its licensors.',
  termsContentTwo: 'The user grants the system owner a license to use uploaded content as needed to operate the service, display it to guests, send it, store it, back it up, provide technical support, and protect legal rights.',
  termsContentThree: 'The user must not upload content that infringes rights, is misleading, offensive, unlawful, viral, harmful, or includes information the user is not authorized to provide.',
  termsAvailabilityTitle: 'Availability, security, and changes',
  termsAvailabilityOne: 'The service is provided as-is and as available from time to time. There is no guarantee that the service will be continuous, fully secure, error-free, suitable for every need, or available at all times.',
  termsAvailabilityTwo: 'The system owner may change, stop, update, delete, restrict, or charge for service components at any time, subject to law, without liability for indirect damage resulting from that action.',
  termsAvailabilityThree: 'The user is responsible for testing before sending invitations, verifying event details, links, numbers, text, and views, and keeping a backup of important information outside the system.',
  termsLiabilityTitle: 'Liability',
  termsLiabilityOne: 'To the maximum extent permitted by law, the system owner will not be liable for any direct, indirect, special, consequential, punitive, or business damage, including lost profits, reputational harm, data loss, event disruption, guest no-shows, or message sending failures.',
  termsLiabilityTwo: 'The system owner is not responsible for acts or omissions of users, guests, event suppliers, third-party services, communication providers, Google, WhatsApp, Waze, Bit, or any external party.',
  termsLiabilityThree: 'If liability is nevertheless imposed on the system owner, total cumulative liability will be limited to the amount actually paid by the user for the service during the three months before the event giving rise to the claim, or NIS 100, whichever is lower.',
  termsLiabilityFour: 'The user acknowledges that without these liability limits, the system owner would not provide the service or would price it differently.',
  termsIndemnityTitle: 'Indemnity and defense',
  termsIndemnityOne: 'The user agrees to indemnify, defend, and compensate the system owner, its employees, managers, suppliers, and representatives for any demand, claim, damage, fine, expense, or legal fee arising from user activity, sent messages, uploaded data, or breach of these terms or law.',
  termsIndemnityTwo: 'The indemnity applies to claims by guests, authorities, third-party providers, rights holders, other users, or anyone allegedly harmed by the user actions.',
  termsTerminationTitle: 'Suspension, deletion, and termination',
  termsTerminationOne: 'The system owner may suspend or terminate an account, delete data, or restrict access in case of breach, suspected breach, debt, security risk, authority request, complaint, or use that harms the service.',
  termsTerminationTwo: 'The user may request account and data deletion, subject to information the system owner may or must retain for records, security, billing, legal compliance, and defense against claims.',
  termsTerminationThree: 'Termination does not affect liability, privacy, intellectual property, indemnity, governing law, jurisdiction, or any section intended by nature to survive.',
  termsChangesTitle: 'Terms updates',
  termsChangesOne: 'The system owner may update these terms from time to time. Continued use after an update means acceptance of the updated terms.',
  termsChangesTwo: 'For a material change, the system may require renewed approval before continued use.',
  termsLawTitle: 'Governing law and jurisdiction',
  termsLawOne: 'These terms and use of the service are governed only by the laws of the State of Israel, without conflict-of-law rules.',
  termsLawTwo: 'Exclusive jurisdiction for any dispute will be in the competent courts of the Tel Aviv-Jaffa district, unless mandatory law requires otherwise.',
  logout: 'Logout',
  dangerZone: 'Danger zone',
  deleteAccount: 'Delete this user data',
  deleteAccountDescription: 'This permanently deletes this host, all events, guests, WhatsApp session data, and related records from the system.',
  deleteAccountConfirm: 'This action permanently deletes the current user and all related data. Continue?',
  deleteAccountPrompt: 'Type DELETE to confirm permanent deletion.',
  deleteCancelled: 'Deletion cancelled',
  deleteCancelledMessage: 'No data was deleted.',
  accountDeleted: 'User data deleted',
  deletedEvents: 'Deleted events',
  deletedGuests: 'Deleted guests',
  cancel: 'Cancel',
  logoutTitle: 'Leave the system?',
  logoutDescription: 'You are about to sign out of the admin dashboard.',
  logoutDataNotice: 'This does not delete events, guests, invitations, or WhatsApp settings. You can sign in again anytime.',
  deleteAccountModalTitle: 'Permanently delete this user?',
  invalidEventName: 'Use 2-160 letters or numbers for the event name.',
  invalidDate: 'Choose a valid date.',
  invalidVenue: 'Use 2-160 letters or numbers for the venue.',
  invalidPhone: 'Use a valid Israeli phone number, for example 050-000-0000.',
  invalidGuestCount: 'Enter a positive number.',
  helpCenter: 'Help center',
  helpIntro: 'Quick answers for the main workflows in the system.',
  startSystemTour: 'Open product tour',
  faqCreateEventQuestion: 'How do I create a new event?',
  faqCreateEventAnswer: 'Open Events, choose New event, fill in the event details, phone number, address, and estimated guest count. The address is used to prepare the Waze flow.',
  faqGuestLoginQuestion: 'Does a guest need to sign in?',
  faqGuestLoginAnswer: 'No. Every guest receives a personal invitation link and can confirm, decline, or choose maybe without opening an account.',
  faqInviteIdQuestion: 'How do we know which guest confirmed?',
  faqInviteIdAnswer: 'Every guest has a unique invite ID. The RSVP link is personal, so the system can connect the response to the right guest.',
  faqWhatsappQuestion: 'How does WhatsApp connection work?',
  faqWhatsappAnswer: 'The event host connects their own WhatsApp account from the WhatsApp screen. The connection is saved to their account, and messages are sent gradually with a small delay.',
  faqGoogleQuestion: 'How do Google contacts work?',
  faqGoogleAnswer: 'The Google button opens Google authorization. After approval, contacts are loaded from Google Contacts and the event host chooses who should receive messages.',
  faqApprovalQuestion: 'Why can an admin be blocked from login?',
  faqApprovalAnswer: 'New admins wait for super admin approval. After approval, they can sign in and manage their own events.',
  faqDemoQuestion: 'What is demo mode?',
  faqDemoAnswer: 'Demo mode has one sample event and lets you try the flow without saving anything to the database.',
  faqOwnerQuestion: 'What can the super admin see?',
  faqOwnerAnswer: 'The super admin can monitor users and events across the system, but cannot access or operate users WhatsApp connections.',
  completeProfileTitle: 'Complete your profile',
  completeProfileDescription: 'Before continuing, add your name and phone number so the account is clear and ready for event management.',
  editProfileTitle: 'User profile',
  editProfileDescription: 'Update your account details. These details belong to the admin user, not to a specific event.',
  saveProfile: 'Save profile',
  profileSaved: 'Profile saved',
  profileSavedMessage: 'Your user details were updated. The name in the top bar now uses the saved full name.',
  profileValidationBlocked: 'Some profile details are missing or invalid. Fix the fields above to continue.',
  invalidEmail: 'Enter a valid email address.',
  invalidFullName: 'Use 2-80 letters for the full name.',
  termsConsentTitle: 'Terms approval',
  termsConsentIntro: 'Please read the terms before using the system. We save this approval in a cookie for this user.',
  termsReadAndAccepted: 'I read the terms and approve using the system.',
  termsScrollToApprove: 'Scroll through the terms to enable approval.',
  confirmApproval: 'I read and approve',
  invalidCredentials: 'Email or password is incorrect.',
  invalidCredentialsHint: 'Check the details and try again.',
  waitingApprovalError: 'This admin account is still waiting for super admin approval.',
  waitingApprovalHint: 'You will receive an email after approval.',
  emailAlreadyUsed: 'This email is already connected to another admin account.',
  emailAlreadyUsedHint: 'Use a different email or sign in with the existing account.',
  networkError: 'Could not reach the server. Check that the backend is running and try again.',
  networkErrorHint: 'If it keeps happening, verify the API URL in the environment file.',
  sessionExpired: 'Your session expired. Please sign in again.',
  sessionExpiredHint: 'This protects your account from stale sessions.',
  genericError: 'Something went wrong. Please try again in a moment.',
  genericErrorHint: 'The action was not completed.',
  permissionDenied: 'You do not have permission to perform this action.',
  permissionDeniedHint: 'Ask the super admin to approve the required access.',
  notFoundError: 'The requested item was not found.',
  notFoundHint: 'Refresh the screen and try again.',
  validationError: 'Some details are not valid.',
  validationErrorHint: 'Check the highlighted fields and correct them.',
  systemLogs: 'System logs',
  systemLogsDescription: 'Structured backend and frontend logs with filters prepared for Elastic-style observability.',
  refreshLogs: 'Refresh logs',
  logLevel: 'Level',
  logSource: 'Source',
  logCategory: 'Category',
  requestId: 'Request ID',
  requestPath: 'Request',
  requestStatus: 'Status',
  requestType: 'Request type',
  message: 'Message',
  applyFilters: 'Apply filters',
  cookieConsentTitle: 'Cookies and local storage',
  cookieConsentDescription: 'We use cookies and local storage to remember approvals, session state, language, and essential system preferences.',
  cookieConsentAccept: 'Approve cookies',
  onboardingTitle: 'Quick product tour',
  onboardingDescription: 'A short walkthrough of the main actions: create an event, invite guests, send messages, and collect RSVPs.',
  onboardingSavedHint: 'Your choice is saved to your account',
  onboardingCompletedTitle: 'Tour completed',
  onboardingCompletedMessage: 'Great, we saved that you finished the product tour. You can keep working normally.',
  onboardingSkippedTitle: 'Tour skipped',
  onboardingSkippedMessage: 'No problem, you can open the product tour again from the help icon.',
  onboardingEventsTitle: 'Create an event',
  onboardingEventsText: 'Create an event, choose date, venue, address, phone number, and event theme. This becomes the base for invitations and guests.',
  onboardingGuestsTitle: 'Manage guests',
  onboardingGuestsText: 'Add guests, track RSVP status, personal invite IDs, and the allowed guest count for each family.',
  onboardingInvitationsTitle: 'Invitation studio',
  onboardingInvitationsText: 'Choose an event theme, edit copy, preview the guest experience, and save event-specific invitation text.',
  onboardingWhatsappTitle: 'Send messages',
  onboardingWhatsappText: 'Connect WhatsApp, choose Google contacts or add guests manually, and send messages one by one with a delay.',
  onboardingSeatingTitle: 'Guest seating',
  onboardingSeatingText: 'Create tables, set capacity, and assign confirmed guests to build a clear seating picture.',
  skipOnboarding: 'Skip tour',
  finishOnboarding: 'Done',
  openFeature: 'Open feature',
  next: 'Next',
  back: 'Back',
} as const;
